### ISSUE TITLE
draw honey-badger mascot logo for website + github repo readme

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#12]
Obviously we should have a smartass looking honey badger drawing. Some quotes about honey badgers from wikipedia - https://en.wikipedia.org/wiki/Honey_badger :

"Honey badgers have even been known to chase away young lions and take their kills."

"They kill and eat snakes, even highly venomous or large ones such as cobras. "

"As with other mustelids of relatively large size, such as wolverines and badgers, honey badgers are notorious for their strength, ferocity and toughness. They have been known to savagely and fearlessly attack almost any kind of animal when escape is impossible, reportedly even repelling much larger predators such as lions."

"They are virtually tireless in combat and can wear out much larger animals in physical confrontations."

**Comment by david415** [comment]
a volunteer contributor is going to soon submit some honey badger drawings... original in svg format.

**Comment by david415** [comment]
done. we need to properly attribute the author of the drawing... and link to their license of choice in this case the creative commons license... but that is a separate issue.

**Comment by hinterlandr** [comment]
Greets, one and all. Art contributor here. Let me know if there are any additional elements needed, or if you have ideas for enhancing visual elements.
