### ISSUE TITLE
OpenBSD compatibility testing

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#38]
Is it true that golang's gopacket does not work in OpenBSD?

If this report is correct then honeyBadger will not run in OpenBSD... and that would be unfortunate. Please look into properly building gopacket under OpenBSD... and report the results here. Thanks!

**Comment by mischief** [comment]
see google/gopacket#64

**Comment by david415** [comment]
excellent! let's write an openbsd INSTALL section in the honeybadger docs...

**Comment by david415** [comment]
or instead why don't you make your patch to libpcap available and I'll link to it in the docs so folks running OpenBSD have a better chance of getting HoneyBadger to run.
