### ISSUE TITLE
"beta test" INSTALL and usage docs

### ISSUE THREAD

**Issue by david415** [david415/HoneyBadger#68]
Need someone to install honeybadger with these directions and tell me if it is clear and makes sense:

We need to improve the installation and usage documentation...?
It lives here:
https://github.com/david415/HoneyBadger_docs

(hopefully leif won't be annoyed i assigned this issue to him without asking him nicely first ;-)

**Comment by DrWhax** [comment]
I can help if needed!

**Comment by david415** [comment]
yess please do.

**Comment by david415** [comment]
so far i've written some usage notes for running on openbsd, freebsd and linux.
